//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class HospitalEntities : DbContext
    {
        public HospitalEntities()
            : base("name=HospitalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cirujia> cirujia { get; set; }
        public virtual DbSet<doctor> doctor { get; set; }
        public virtual DbSet<enfermera> enfermera { get; set; }
        public virtual DbSet<paciente> paciente { get; set; }
        public virtual DbSet<quirofano> quirofano { get; set; }
        public virtual DbSet<Enfermedad> Enfermedad { get; set; }
    
        public virtual int AumentarSalario(Nullable<int> idp, Nullable<int> aumento)
        {
            var idpParameter = idp.HasValue ?
                new ObjectParameter("idp", idp) :
                new ObjectParameter("idp", typeof(int));
    
            var aumentoParameter = aumento.HasValue ?
                new ObjectParameter("aumento", aumento) :
                new ObjectParameter("aumento", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AumentarSalario", idpParameter, aumentoParameter);
        }
    
        public virtual int CobrarIva(Nullable<int> iva)
        {
            var ivaParameter = iva.HasValue ?
                new ObjectParameter("iva", iva) :
                new ObjectParameter("iva", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CobrarIva", ivaParameter);
        }
    }
}
